name: Client CI

on:
  pull_request:
    branches: [master]
    paths:
      - 'client/**'

jobs:
  client:
    runs-on: ubuntu-latest
    name: Client Checks

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # or whatever version your project uses

      - name: Install dependencies
        working-directory: client
        run: pnpm install

      - name: Run Lint
        working-directory: client
        run: pnpm lint

      - name: Check Format
        working-directory: client
        run: pnpm format --check

      - name: Build
        working-directory: client
        run: pnpm build
